"""add task priority

Revision ID: 8615aedc2c3c
Revises: 10e556f43a1d
Create Date: 2026-09-02 09:42:07.339583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8615aedc2c3c'
down_revision: Union[str, Sequence[str], None] = '10e556f43a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'priority')
    # ### end Alembic commands ###
